version: "3"

services:
  redis:
    image: redis:5
    ports:
      - "6379:6379"
    command:
      redis-server
  keycloak:
    image: jboss/keycloak:9.0.2
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
